benchmarks: benchmark.cpp File Reference
benchmark.cpp File Reference
#include "lib/montecarlo.hpp"
#include "lib/primes.hpp"
#include "lib/sys.hpp"
#include "lib/threadpool.hpp"
#include <chrono>
#include <cstring>
#include <ctime>
#include <fstream>
#include <iostream>
#include <limits.h>
#include <thread>
#include <unistd.h>
#include <vector>
Functions
void bench_naive_primes (std::vector< uint32_t > nums)
void bench_threadpool_primes (std::vector< uint32_t > nums)
void bench_monte_carlo ()
void daemon (int interval)
void usage (const char *programName)
int main (int argc, char *argv[])
Variables
std::vector< uint32_t > nums
Function Documentation
bench_monte_carlo()
void bench_monte_carlo ()
Definition at line 136 of file benchmark.cpp.
{
     int trials_per_thread = 4096;
     int threads = 256;
     int blocks = 256;
     int total_trials = trials_per_thread * threads * blocks;
     std::cout << "Trials/thread: " << trials_per_thread << std::endl;
     std::cout << "Threads: " << threads << std::endl;
     std::cout << "Blocks: " << blocks << std::endl;
     std::cout << "Total trials: " << total_trials << std::endl;
     auto start_time = std::chrono::high_resolution_clock::now();
     double predicted_pi = monte_carlo(total_trials);
     auto end_time = std::chrono::high_resolution_clock::now();
     std::chrono::duration<double> elapsed_time = end_time - start_time;
     std::cout << "Estimated value of pi: " << predicted_pi
               << " in : " << elapsed_time.count() << " seconds" << std::endl;
     long double err = predicted_pi - PI;
     std::cout << "Error of " << err << std::endl;
 }
References monte_carlo(), and PI.
Referenced by main().
bench_naive_primes()
void bench_naive_primes (std::vector< uint32_t > nums)
Definition at line 77 of file benchmark.cpp.
{
     // TODO at the end of each benchmark run we should log memory
     std::cout << "Miller-Rabin sequential...\n";
     // TIME START
     std::chrono::steady_clock::time_point start_time =
         std::chrono::steady_clock::now();
     for (uint32_t n : nums) {
         if (miller_rabin(n, 120000)) {
             std::cout << n << " is PRIME...\n";
         } else {
             std::cout << n << " is COMPOSITE...\n";
         }
     }
     // TIME END
     std::chrono::steady_clock::time_point end_time =
         std::chrono::steady_clock::now();
     std::cout << "Time elapsed: "
               << std::chrono::duration_cast<std::chrono::milliseconds>(
                      end_time - start_time)
                      .count()
               << " ms" << std::endl;
 }
References miller_rabin(), and nums.
Referenced by main().
bench_threadpool_primes()
void bench_threadpool_primes (std::vector< uint32_t > nums)
Definition at line 103 of file benchmark.cpp.
{
     // declares a threadpool with 4 threads
     ThreadPool *pool = new ThreadPool(4);
     std::vector<std::future<bool>> miller_results;
     std::chrono::steady_clock::time_point start_time =
         std::chrono::steady_clock::now();
     for (auto n : nums) {
         miller_results.emplace_back(
             pool->enqueue([n]() { return miller_rabin(n, 120000); }));
     }
     // print the results
     std::cout << "\nResults:\n";
     std::cout << "Miller-Rabin with ThreadPool" << std::endl;
     for (size_t i = 0; i < miller_results.size(); i++) {
         bool is_prime = miller_results[i].get();
         std::cout << nums[i] << " is " << (is_prime ? "PRIME" : "COMPOSITE")
                   << "\n";
     }
     delete pool;
     std::chrono::steady_clock::time_point end_time =
         std::chrono::steady_clock::now();
     std::cout << "Time elapsed: "
               << std::chrono::duration_cast<std::chrono::milliseconds>(
                      end_time - start_time)
                      .count()
               << " ms" << std::endl;
 }
References ThreadPool::enqueue(), and nums.
Referenced by main().
daemon()
void daemon (int interval)
Definition at line 286 of file benchmark.cpp.
{
     // System class obj
     System sys;
     // CPU/PROC INFO, POPULATES VARIOUS CLASS VARS
     sys.cpu_info();     // get once outside of main loop
     // fetch hostname and current user
     char host[HOST_NAME_MAX];
     char user[LOGIN_NAME_MAX];
     gethostname(host, HOST_NAME_MAX);
     getlogin_r(user, LOGIN_NAME_MAX);
     // float starting_cpu_temp = sys.cpu_idle_temp();
     // float starting_cpu_usg = sys.cpu_load();
     // std::cout << starting_cpu_temp << starting_cpu_usg << std::endl;
     // infinite loop for continuous collection
     while (true) {
         // GET CURRENT DATE FMT IN mmddyyyy
         // this will rely on system timezone (/etc/timezone)
         auto now = std::chrono::system_clock::now();
         std::time_t time = std::chrono::system_clock::to_time_t(now);
         std::tm local_tm = *std::localtime(&time);
         // extract info for date and time
         char date_str[9]; // MMDDYYYY + '\0'
         char time_str[7]; // HHMMSS + '\0'
         std::strftime(date_str, sizeof(date_str), "%m%d%Y", &local_tm);
         std::strftime(time_str, sizeof(time_str), "%H%M%S", &local_tm);
         // CSV FILE NAME with only the date
         std::string filename = std::string(user) + "_" + std::string(host) +
             std::string(date_str) + ".csv";
         // open CSV to append
         std::ofstream csvFile(filename, std::ios::app);
         if (csvFile.is_open()) {
             // If the file is empty, add headers
             if (csvFile.tellp() == 0) {
                 csvFile << "TIME,CPU_MODEL,NUM_CPUs,PROCS,BogoMIPS,CPU_USG,"
                         << "CPU_TEMP,TOTAL_VRAM,USED_VRAM,FREE_VRAM,"
                         << "TOTAL_RAM,USED_RAM,FREE_RAM\n";
 #ifdef __HAS_NVCC__
                 csvFile << "GPU_MODEL,"
                         << ",TOTAL_GPU_MEM,USED_GPU_MEM, FREE_GPU_MEM"
                         ;
 #endif
             }
             // CURRENT MEMORY USAGE, THIS METHOD POPULATE VARIOUS CLASS VARS
             sys.mem_stats();
             // CPU/PROC INFO, POPULATES VARIOUS CLASS VARS
             sys.cpu_info();
             // WRITE ALL INFO TO CSV FILE
             csvFile << time             << ","  // time
                     << sys.cpu_model    << ","  // CPU model
                     << sys.num_proc     << ","  // number of CPUs
                     << sys.ps_count()   << ","  // process count
                     << sys.bogus_mips   << ","  // bogoMIPS
                     << sys.cpu_load()   << ","  // CPU load %
                     << sys.cpu_temp()   << ","  // CPU temp
                     << sys.v_mem_total  << ","  // VRAM total
                     << sys.v_mem_used   << ","  // VRAM used
                     << sys.v_mem_free   << ","  // VRAM free
                     << sys.p_mem_total  << ","  // RAM total
                     << sys.p_mem_used   << ","  // RAM USED
                     << sys.p_mem_free           // RAM free
                     ;
 #ifdef __HAS_NVCC__
             // additional GPU information
             //csvFile << "," << sys.gpu_mem_total  // GPU VRAM total
             //        << "," << sys.gpu_mem_used   // GPU VRAM used
             //        << "," << sys.gpu_mem_free;  // GPU VRAM free
 #endif
             // move to next line
             csvFile << "\n";
             // close file
             csvFile.close();
         } else {
             std::cerr << "Error: Unable to open file " << filename
                       << " for writing.\n";
         }
         // sleep
         std::this_thread::sleep_for(std::chrono::seconds(interval));
     }
 }
References System::bogus_mips, System::cpu_info(), System::cpu_load(), System::cpu_model, System::cpu_temp(), System::mem_stats(), System::num_proc, System::p_mem_free, System::p_mem_total, System::p_mem_used, System::ps_count(), System::v_mem_free, System::v_mem_total, and System::v_mem_used.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 392 of file benchmark.cpp.
{
     if (argc < 2) {
         usage(argv[0]);
         exit(EXIT_FAILURE);
     }
     else {
         if (strcmp(argv[1], "-b") == 0) {
             std::cout << "Starting benchmark...\n\n";
             if (argc < 3) {
                 std::cerr
                     << "Error: Specify 'cpu' or 'gpu' after the -b flag.\n";
                 exit(EXIT_FAILURE);
             }
             std::string mode(argv[2]);
             // System class obj
             System sys;
             // if -b cpu
             if (mode == "cpu") {
                 std::cout << "<--------- CPU TESTS --------->\n";
                 // display CPU information and number of running processes from
                 // `ps`
                 sys.cpu_info();
                 sys.ps_count();
                 sys.cpu_usage();
                 sys.mem_info();
                 sys.cpu_temp();
                 // TODO get idle temperature at the start of this benchmark to
                 // determine the "idle starting" temperature. store in struct?
                 // when would it get called?
                 // TODO FIXME I am thinking this system info should be logged
                 // from a separate thread
                 std::cout << "Primality tests with Miller-Rabin algorithm...\n";
                 bench_naive_primes(nums);
                 bench_threadpool_primes(nums);
                 // TODO where/when should these be called? should these
                 // functions update values located within a struct? think about
                 // this...
                 sys.cpu_usage();
                 sys.mem_info();
                 sys.cpu_temp();
                 std::cout << "Pi estimation using Monte Carlo methods...\n";
                 bench_monte_carlo();
                 sys.cpu_usage();
                 sys.mem_info();
                 sys.cpu_temp();
                 std::cout << "Discrete Fourier Transform...\n";
                 std::cout << "Fast Fourier Transform...\n";
                 // TODO: finish out some openGPMP matrix operations for this
                 // to compare against the F90 methods, openBLAS, and finally
                 // corresponding GPU implementations.
                 // Include benchmarks against Naive Implementations as well
                 std::cout << "Matrix...\n";
             }
             // if -b gpu
             else if (mode == "gpu") {
                 // if host has NVCC installed
 #ifdef __HAS_NVCC__
                 std::cout << "<--------- GPU TESTS --------->\n";
                 std::cout << "NVIDIA device found!\n";
                 gpu_bench_monte_carlo();
                 gpu_bench_miller_rabin();
 #else
                 std::cout << "No NVIDIA device found!\n";
 #endif
             }
             else {
                 std::cerr << "Error: Invalid mode. Specify 'cpu' or 'gpu' after -b flag\n";
                 exit(EXIT_FAILURE);
             }
         }
         // daemon
         if (strcmp(argv[1], "-d") == 0) {
             // TODO implement "daemon"
             std::cout << "Running as daemon...\n";
             daemon(2);
         }
     }
     return 0;
 }
References bench_monte_carlo(), bench_naive_primes(), bench_threadpool_primes(), System::cpu_info(), System::cpu_temp(), System::cpu_usage(), daemon(), System::mem_info(), nums, System::ps_count(), and usage().
usage()
void usage (const char * programName)
Definition at line 379 of file benchmark.cpp.
{
     std::cout << "Usage: " << programName
               << " [-d | -b cpu | gpu ] -o" << std::endl;
     std::cout << "  -d : daemon mode to monitor system information\n";
     std::cout << "  -b : benchmark mode to run system stress tests with live "
                  "monitoring\n";
     std::cout << "    cpu - run CPU-based benchmarks\n";
     std::cout << "    gpu - run GPU-based benchmarks\n";
     std::cout << "  -o : output file\n";
 }
Referenced by System::cpu_load(), and main().
Variable Documentation
nums
std::vector<uint32_t> nums
Driver for this benchmarks project featuring cmd line options and functions for benchmark program runs...
-d (DAEMON) live system monitoring -b (BENCHMARK) run benchmark system stress programs
Definition at line 36 of file benchmark.cpp.
Referenced by bench_naive_primes(), bench_threadpool_primes(), and main().