benchmarks: System Class Reference
System Class Reference
#include <sys.hpp>
Public Member Functions
std::string read_file (const std::string &filename)
reads the contents of a file into a string
int proc_info ()
get number of running processes on the system
void cpu_usage ()
get CPU usage using load average read from /proc/loadavg calculating CPU and IO utilization over the last
void cpu_info ()
get CPU info, BogoMIPS and Model
void mem_info ()
get memory info and stats from /proc/meminfo
double cpu_temp ()
get current CPU temperature from /sys/class/thermal/thermal_zone0/temp
double cpu_idle_temp ()
get idle CPU temp based on a 20 second cooldown
void cpu_idle (double idle_temp)
pause program execution until idle CPU temp is reached
double cpu_stats ()
get CPU usage
void mem_stats ()
Public Attributes
double cpu_temp_idle
float cpu_use
uint64_t v_mem_total
uint64_t v_mem_used
uint64_t v_mem_free
uint64_t p_mem_total
uint64_t p_mem_used
uint64_t p_mem_free
Detailed Description
Definition at line 5 of file sys.hpp.
Member Function Documentation
cpu_idle()
void System::cpu_idle (double idle_temp)
pause program execution until idle CPU temp is reached
Parameters
idle_temp idle CPU temp
Definition at line 177 of file sys.cpp.
{
     while (true) {
         double temp_now = cpu_temp();
         if (temp_now <= idle_temp) {
             break;
         }
         std::this_thread::sleep_for(std::chrono::seconds(1));
     }
 }
References cpu_temp().
cpu_idle_temp()
double System::cpu_idle_temp ()
get idle CPU temp based on a 20 second cooldown
Returns
idle CPU temp
Definition at line 145 of file sys.cpp.
{
     std::cout << "Determining idle CPU temperature...\n";
     int duration = 20;
     std::vector<double> temperatures;
     auto time_start = std::chrono::steady_clock::now();
     while (true) {
         auto time_now = std::chrono::steady_clock::now();
         auto time_elapsed = std::chrono::duration_cast<std::chrono::seconds>(
                                 time_now - time_start)
                                 .count();
         if (time_elapsed >= duration) {
             break;
         }
         double temperature = cpu_temp();
         temperatures.push_back(temperature);
         std::this_thread::sleep_for(std::chrono::seconds(1));
     }
     double sum = 0.0;
     for (const double &temp : temperatures) {
         sum += temp;
     }
     double idle_temp = sum / temperatures.size();
     // set class var
     //System::cpu_temp_idle = idle_temp;
     return idle_temp;
 }
References cpu_temp().
cpu_info()
void System::cpu_info ()
get CPU info, BogoMIPS and Model
Definition at line 62 of file sys.cpp.
                       {
     std::string lscpu_output;
     std::string model;
     double bogoMIPS = 0.0;
     int numCPUs = 0;
     // run the lscpu command and capture its output
     FILE *pipe = popen("lscpu", "r");
     if (pipe) {
         char buffer[128];
         while (!feof(pipe)) {
             if (fgets(buffer, 128, pipe) != nullptr) {
                 lscpu_output += buffer;
             }
         }
         pclose(pipe);
         // parse lscpu output to extract information
         size_t pos = 0;
         while (pos < lscpu_output.size()) {
             size_t newline_pos = lscpu_output.find('\n', pos);
             if (newline_pos == std::string::npos) {
                 newline_pos = lscpu_output.size();
             }
             std::string line = lscpu_output.substr(pos, newline_pos - pos);
             // convert the line to lowercase for case-insensitive matching
             std::transform(line.begin(), line.end(), line.begin(), ::tolower);
             if (line.find("model name") != std::string::npos) {
                 // extract model name
                 size_t colon_pos = line.find(":");
                 if (colon_pos != std::string::npos) {
                     model = line.substr(colon_pos + 1);
                     model = model.substr(model.find_first_not_of(" \t"),
                                          model.find_last_not_of(" \t") + 1);
                 }
             } else if (line.find("bogomips") != std::string::npos) {
                 // extract BogoMIPS value
                 size_t colon_pos = line.find(":");
                 if (colon_pos != std::string::npos) {
                     bogoMIPS = std::stod(line.substr(colon_pos + 1));
                 }
             } else if (line.find("cpu(s):") != std::string::npos) {
                 // extract the number of CPU(s)
                 size_t colon_pos = line.find(":");
                 if (colon_pos != std::string::npos) {
                     numCPUs = std::stoi(line.substr(colon_pos + 1));
                 }
             }
             pos = newline_pos + 1;
         }
         // print the extracted information
         std::cout << "CPU model: " << model << std::endl;
         std::cout << "BogoMIPS: " << bogoMIPS << std::endl;
         std::cout << "Number of CPU(s): " << numCPUs << std::endl;
     } else {
         std::cerr << "Failed to run lscpu command." << std::endl;
     }
 }
Referenced by main().
cpu_stats()
double System::cpu_stats ()
get CPU usage
Returns
usage as a percentage
Definition at line 189 of file sys.cpp.
{
     std::ifstream file("/proc/stat");
     if (!file.is_open()) {
         std::cerr << "Failed to open /proc/stat" << std::endl;
         return -1.0;
     }
     std::string line;
     std::getline(file, line);
     std::istringstream iss(line);
     std::string cpuLabel;
     iss >> cpuLabel;
     if (cpuLabel != "cpu") {
         std::cerr << "Failed to parse /proc/stat" << std::endl;
         return -1.0;
     }
     std::vector<uint64_t> values;
     uint64_t value;
     while (iss >> value) {
         values.push_back(value);
     }
     if (values.size() < 7) {
         std::cerr << "Failed to parse /proc/stat" << std::endl;
         return -1.0;
     }
     uint64_t idle = values[3];
     uint64_t total = 0;
     for (int i = 0; i < 7; i++) {
         total += values[i];
     }
     // Calculate CPU usage as a percentage
     double usage = 100.0 * (1.0 - static_cast<double>(idle) / total);
     //std::cout << "CPU USAGE: " << usage << std::endl;
     return usage;
 }
References usage().
Referenced by daemon().
cpu_temp()
double System::cpu_temp ()
get current CPU temperature from /sys/class/thermal/thermal_zone0/temp
Definition at line 126 of file sys.cpp.
{
     // TODO initialize starting temp here?
     std::string cpu_temp = read_file("/sys/class/thermal/thermal_zone0/temp");
     if (!cpu_temp.compare(0, 5, "Error")) {
         std::cout << "Error reading CPU temperature." << std::endl;
     } else {
         float temp_c = std::stof(cpu_temp) / 1000.0; // convert to Celsius
         //float temp_f = (temp_c * 9 / 5) + 32;        // convert to Fahrenheit
         // std::cout << "CPU Temperature: " << temp_c << "°C"
         //          << " (" << temp_f << "°F)" << std::endl;
         return temp_c;
     }
     return -1;
 }
References read_file().
Referenced by cpu_idle(), cpu_idle_temp(), daemon(), and main().
cpu_usage()
void System::cpu_usage ()
get CPU usage using load average read from /proc/loadavg calculating CPU and IO utilization over the last
1 / 5 / 10 min, number of running/total processes, last PID 0.20 0.18 0.12 1/80 11206
Definition at line 56 of file sys.cpp.
{
     std::string cpu_usage = read_file("/proc/loadavg");
     std::cout << "CPU Usage (load average): " << cpu_usage;
 }
References read_file().
Referenced by main().
mem_info()
void System::mem_info ()
get memory info and stats from /proc/meminfo
Definition at line 232 of file sys.cpp.
                       {
     std::ifstream meminfo_file("/proc/meminfo");
     if (meminfo_file.is_open()) {
         std::string line;
         std::vector<std::string> fetched_stats =
             {"MemTotal:", "MemFree:", "MemAvailable:", "Buffers:", "Cached:"};
         while (std::getline(meminfo_file, line)) {
             for (const std::string &stat : fetched_stats) {
                 if (line.find(stat) == 0) {
                     std::cout << line << std::endl;
                 }
             }
         }
     } else {
         std::cerr << "Failed to read /proc/meminfo." << std::endl;
     }
 }
Referenced by main(), and mem_stats().
mem_stats()
void System::mem_stats ()
Definition at line 252 of file sys.cpp.
{
     struct sysinfo mem_info;
     sysinfo(&mem_info);
     uint64_t virt_total =
         (mem_info.totalram + mem_info.totalswap) * mem_info.mem_unit;
     uint64_t virt_used = (mem_info.totalram - mem_info.freeram +
                                 mem_info.totalswap - mem_info.freeswap) *
                                mem_info.mem_unit;
     uint64_t phys_total = mem_info.totalram * mem_info.mem_unit;
     uint64_t phys_used =
         (mem_info.totalram - mem_info.freeram) * mem_info.mem_unit;
     // VIRTUAL MEM in KB
     System::v_mem_total = virt_total / 1000;
     System::v_mem_used = virt_used / 1000;
     System::v_mem_free = (virt_total - virt_used) / 1000;
     // PHYSICAL MEM in KB
     System::p_mem_total = phys_total / 1000;
     System::p_mem_used = phys_used / 1000;
     System::p_mem_free = (phys_total - phys_used) / 1000;
 }
References mem_info(), p_mem_free, p_mem_total, p_mem_used, v_mem_free, v_mem_total, and v_mem_used.
Referenced by daemon().
proc_info()
int System::proc_info ()
get number of running processes on the system
Returns
number of running processes or error code
Definition at line 35 of file sys.cpp.
                       {
     FILE *proc_pipe = popen("ps aux | wc -l", "r");
     if (!proc_pipe) {
         std::cerr << "popen failed for processes." << std::endl;
         return -1;
     }
     char proc_buffer[128];
     if (fgets(proc_buffer, sizeof(proc_buffer), proc_pipe) != nullptr) {
         int num_proc = std::stoi(proc_buffer);
         pclose(proc_pipe);
         std::cout << "Number of running processes: " << num_proc << std::endl;
         return num_proc;
     } else {
         std::cerr << "Failed to read the output of 'ps'." << std::endl;
         pclose(proc_pipe);
         return -1;
     }
 }
Referenced by main().
read_file()
std::string System::read_file (const std::string & filename)
reads the contents of a file into a string
Parameters
filename path to the file to be read
Returns
string containing the contents of the file if successful, or an error message if the file cannot be opened or read
File containing functions to display system information TODO: figure out logic behind collecting information (to variables) and dumping them en masse to a file. this should be done logically with some sort of interval / condition on collecting data to log i.e.:
before benchmark test
during test (how often?, pause/resume timers before/after check_mem call?)
after test
Definition at line 23 of file sys.cpp.
{
     std::ifstream file(filename);
     if (!file.is_open()) {
         return "Error: Unable to read " + filename;
     }
     std::ostringstream buffer;
     buffer << file.rdbuf();
     return buffer.str();
 }
Referenced by cpu_temp(), and cpu_usage().
Member Data Documentation
cpu_temp_idle
double System::cpu_temp_idle
Idle CPU temp set in cpu_idle_temp()
Definition at line 8 of file sys.hpp.
cpu_use
float System::cpu_use
Definition at line 9 of file sys.hpp.
p_mem_free
uint64_t System::p_mem_free
Definition at line 18 of file sys.hpp.
Referenced by daemon(), and mem_stats().
p_mem_total
uint64_t System::p_mem_total
Definition at line 16 of file sys.hpp.
Referenced by daemon(), and mem_stats().
p_mem_used
uint64_t System::p_mem_used
Definition at line 17 of file sys.hpp.
Referenced by daemon(), and mem_stats().
v_mem_free
uint64_t System::v_mem_free
Definition at line 13 of file sys.hpp.
Referenced by daemon(), and mem_stats().
v_mem_total
uint64_t System::v_mem_total
Definition at line 11 of file sys.hpp.
Referenced by daemon(), and mem_stats().
v_mem_used
uint64_t System::v_mem_used
Definition at line 12 of file sys.hpp.
Referenced by daemon(), and mem_stats().
The documentation for this class was generated from the following files:
lib/sys.hpp
src/sys.cpp