benchmarks: primes.cpp File Reference
primes.cpp File Reference
#include "lib/primes.hpp"
#include <iostream>
#include <random>
#include <vector>
Functions
uint32_t mod_mul (uint32_t a, uint32_t b, uint32_t m)
Utility modulo multiply function finding (a * b) % m.
uint32_t mod_pow (uint32_t a, uint32_t b, uint32_t m)
Utility modulo power function finding (a ^ b) % m.
bool witness (uint32_t n, uint32_t d, uint32_t a, uint32_t s)
witness utility function for miller_rabin checks if a given witness 'a' indicates that 'n' is composite
bool miller_rabin (uint32_t n, uint32_t iters=10)
Modified primes algorithm.
Function Documentation
miller_rabin()
bool miller_rabin (uint32_t n, uint32_t iters)
Modified primes algorithm.
Parameters
n target number (uint64_t)
iters iterations determine accuracy (uint64_t)
return true/false (bool)
Definition at line 49 of file primes.cpp.
{
     if (n < 2) {
         return false;
     }
     if (n == 2 || n == 3) {
         return true;
     }
     if (n % 2 == 0) {
         return false;
     }
     uint32_t d = n - 1, s = 0;
     while (d % 2 == 0) {
         d /= 2;
         s++;
     }
     for (uint32_t i = 0; i < iters; i++) {
         uint32_t a = rand() % (n - 3) + 2;
         if (witness(n, d, a, s)) {
             return false;
         }
     }
     return true;
 }
References witness().
Referenced by bench_naive_primes(), and bench_threadpool_primes_dispatch().
mod_mul()
uint32_t mod_mul (uint32_t a, uint32_t b, uint32_t m)
Utility modulo multiply function finding (a * b) % m.
Parameters
a first operand of the multiplication
b second operand of the multiplication
m modulus used to limit the result
Returns
result of (a * b) % m
Definition at line 6 of file primes.cpp.
{
     uint32_t res = 0;
     while (b > 0) {
         if (b & 1) {
             res = (res + a) % m;
         }
         a = (2 * a) % m;
         b >>= 1;
     }
     return res;
 }
Referenced by mod_pow(), and witness().
mod_pow()
uint32_t mod_pow (uint32_t a, uint32_t b, uint32_t m)
Utility modulo power function finding (a ^ b) % m.
Parameters
a base for exponentiation
b exponent
m modulus used to limit the result
Returns
result of (a^b) % m
Definition at line 18 of file primes.cpp.
{
     uint32_t res = 1;
     a %= m;
     while (b > 0) {
         if (b & 1) {
             res = mod_mul(res, a, m);
         }
         a = mod_mul(a, a, m);
         b >>= 1;
     }
     return res;
 }
References mod_mul().
Referenced by witness().
witness()
bool witness (uint32_t n, uint32_t d, uint32_t a, uint32_t s)
witness utility function for miller_rabin checks if a given witness 'a' indicates that 'n' is composite
Parameters
n number being tested for primality
d value 'd' computed from 'n' during the primality test
a witness value being tested
s number of times 'd' can be divided by 2 (s = log2(d))
Returns
true/false (bool)
Definition at line 32 of file primes.cpp.
{
     uint32_t x = mod_pow(a, d, n);
     // likely prime, return false
     if (x == 1 || x == n - 1) {
         return false;
     }
     for (uint32_t r = 1; r < s; r++) {
         x = mod_mul(x, x, n);
         if (x == n - 1) {
             return false;
         }
     }
     return true;
 }
References mod_mul(), and mod_pow().
Referenced by miller_rabin().