benchmarks: sys.cpp File Reference
sys.cpp File Reference
#include "sys.hpp"
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>
Functions
std::string read_file (const std::string &filename)
reads the contents of a file into a string
int proc_info ()
get number of running processes on the system
void cpu_usage ()
get CPU usage using load average read from /proc/loadavg calculating CPU and IO utilization over the last
void cpu_info ()
get CPU info, BogoMIPS and Model
void mem_info ()
get memory info and stats from /proc/meminfo
void cpu_temp ()
get current CPU temperature from /sys/class/thermal/thermal_zone0/temp
Function Documentation
cpu_info()
void cpu_info ()
get CPU info, BogoMIPS and Model
Definition at line 52 of file sys.cpp.
                 {
     std::ifstream cpu_info_file("/proc/cpuinfo");
     if (cpu_info_file.is_open()) {
         std::string line;
         std::string model;
         double bogoMIPS = 0.0;
         while (std::getline(cpu_info_file, line)) {
             if (line.find("BogoMIPS") == 0) {
                 // extract BogoMIPS value
                 size_t colon_pos = line.find(":");
                 if (colon_pos != std::string::npos) {
                     bogoMIPS = std::stod(line.substr(colon_pos + 1));
                 }
             }
             else if (line.find("Model") == 0) {
                 // extract model name
                 size_t colon_pos = line.find(":");
                 if (colon_pos != std::string::npos) {
                     model = line.substr(colon_pos + 1);
                 }
             }
         }
         // TODO: get info from lscpu!!
         std::cout << "Model: " << model << std::endl;
         std::cout << "BogoMIPS: " << bogoMIPS << std::endl;
     } else {
         std::cerr << "Failed to read /proc/cpuinfo." << std::endl;
     }
 }
Referenced by main().
cpu_temp()
void cpu_temp ()
get current CPU temperature from /sys/class/thermal/thermal_zone0/temp
Definition at line 105 of file sys.cpp.
                 {
     std::string cpu_temp = read_file("/sys/class/thermal/thermal_zone0/temp");
     if (!cpu_temp.compare(0, 5, "Error")) {
         std::cout << "Error reading CPU temperature." << std::endl;
     } else {
         float temp_c = std::stof(cpu_temp) / 1000.0; // convert to Celsius
         float temp_f = (temp_c * 9 / 5) + 32;       // convert to Fahrenheit
         std::cout << "CPU Temperature: " << temp_c << "°C"
                   << " (" << temp_f << "°F)" << std::endl;
     }
 }
References read_file().
Referenced by main().
cpu_usage()
void cpu_usage ()
get CPU usage using load average read from /proc/loadavg calculating CPU and IO utilization over the last
1 / 5 / 10 min, number of running/total processes, last PID 0.20 0.18 0.12 1/80 11206
Definition at line 46 of file sys.cpp.
                  {
     std::string cpu_usage = read_file("/proc/loadavg");
     std::cout << "CPU Usage (load average): " << cpu_usage;
 }
References read_file().
Referenced by main().
mem_info()
void mem_info ()
get memory info and stats from /proc/meminfo
Definition at line 85 of file sys.cpp.
                 {
     std::ifstream meminfo_file("/proc/meminfo");
     if (meminfo_file.is_open()) {
         std::string line;
         std::vector<std::string> fetched_stats =
             {"MemTotal:", "MemFree:", "MemAvailable:", "Buffers:", "Cached:"};
         while (std::getline(meminfo_file, line)) {
             for (const std::string &stat : fetched_stats) {
                 if (line.find(stat) == 0) {
                     std::cout << line << std::endl;
                 }
             }
         }
     } else {
         std::cerr << "Failed to read /proc/meminfo." << std::endl;
     }
 }
Referenced by main().
proc_info()
int proc_info ()
get number of running processes on the system
Returns
number of running processes or error code
Definition at line 25 of file sys.cpp.
                 {
     FILE *proc_pipe = popen("ps aux | wc -l", "r");
     if (!proc_pipe) {
         std::cerr << "popen failed for processes." << std::endl;
         return -1;
     }
     char proc_buffer[128];
     if (fgets(proc_buffer, sizeof(proc_buffer), proc_pipe) != nullptr) {
         int num_proc = std::stoi(proc_buffer);
         pclose(proc_pipe);
         std::cout << "Number of running processes: " << num_proc << std::endl;
         return num_proc;
     } else {
         std::cerr << "Failed to read the output of 'ps'." << std::endl;
         pclose(proc_pipe);
         return -1;
     }
 }
Referenced by main().
read_file()
std::string read_file (const std::string & filename)
reads the contents of a file into a string
File containing functions to display system information TODO
Definition at line 13 of file sys.cpp.
{
     std::ifstream file(filename);
     if (!file.is_open()) {
         return "Error: Unable to read " + filename;
     }
     std::ostringstream buffer;
     buffer << file.rdbuf();
     return buffer.str();
 }
Referenced by cpu_temp(), and cpu_usage().