benchmarks: sysstats.cpp File Reference
sysstats.cpp File Reference
#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
Functions
std::string readFromFile (const std::string &filename)
int getRunningProcesses ()
void cpu_usage ()
void cpu_info ()
void mem_info ()
void cpu_temp ()
int main ()
Function Documentation
cpu_info()
void cpu_info ()
Definition at line 51 of file sysstats.cpp.
                 {
     std::ifstream cpuInfoFile("/proc/cpuinfo");
     if (cpuInfoFile.is_open()) {
         std::string line;
         std::string model;
         double bogoMIPS = 0.0;
         while (std::getline(cpuInfoFile, line)) {
             if (line.find("BogoMIPS") == 0) {
                 // extract BogoMIPS value
                 size_t colonPos = line.find(":");
                 if (colonPos != std::string::npos) {
                     bogoMIPS = std::stod(line.substr(colonPos + 1));
                 }
             } else if (line.find("Model") == 0) {
                 // extract model name
                 size_t colonPos = line.find(":");
                 if (colonPos != std::string::npos) {
                     model = line.substr(colonPos + 1);
                 }
             }
         }
         std::cout << "Model: " << model << std::endl;
         std::cout << "BogoMIPS: " << bogoMIPS << std::endl;
     } else {
         std::cerr << "Failed to read /proc/cpuinfo." << std::endl;
     }
 }
Referenced by main().
cpu_temp()
void cpu_temp ()
Definition at line 101 of file sysstats.cpp.
                 {
     std::string cpuTemp = readFromFile("/sys/class/thermal/thermal_zone0/temp");
     if (!cpuTemp.compare(0, 5, "Error")) {
         std::cout << "Error reading CPU temperature." << std::endl;
     } else {
         float temp = std::stof(cpuTemp) / 1000.0; // convert to Celsius
         std::cout << "CPU Temperature: " << temp << "°C" << std::endl;
     }
 }
References readFromFile().
Referenced by main().
cpu_usage()
void cpu_usage ()
Definition at line 45 of file sysstats.cpp.
                  {
     std::string cpuUsage = readFromFile("/proc/loadavg");
     std::cout << "CPU Usage (load average): " << cpuUsage;
 }
References readFromFile().
Referenced by main().
getRunningProcesses()
int getRunningProcesses ()
Definition at line 25 of file sysstats.cpp.
{
     FILE* processPipe = popen("ps aux | wc -l", "r");
     if (!processPipe) {
         std::cerr << "popen failed for processes." << std::endl;
         return -1;
     }
     char processBuffer[128];
     if (fgets(processBuffer, sizeof(processBuffer), processPipe) != nullptr) {
         int numProcesses = std::stoi(processBuffer);
         pclose(processPipe);
         return numProcesses;
     } else {
         std::cerr << "Failed to read the output of 'ps'." << std::endl;
         pclose(processPipe);
         return -1;
     }
 }
Referenced by main().
main()
int main ()
Definition at line 111 of file sysstats.cpp.
            {
     // display CPU model and other stats
     cpu_info();
     // get and display the number of running processes
     int numProcesses = getRunningProcesses();
     if (numProcesses != -1) {
         std::cout << "Number of running processes: " << numProcesses << std::endl;
     }
     // display CPU usage, memory statistics, and CPU temperature
     cpu_usage();
     mem_info();
     cpu_temp();
     return 0;
 }
References cpu_info(), cpu_temp(), cpu_usage(), getRunningProcesses(), and mem_info().
mem_info()
void mem_info ()
Definition at line 82 of file sysstats.cpp.
                 {
     std::ifstream meminfoFile("/proc/meminfo");
     if (meminfoFile.is_open()) {
         std::string line;
         std::vector<std::string> desiredStats = {"MemTotal:", "MemFree:", "MemAvailable:", "Buffers:", "Cached:"};
         while (std::getline(meminfoFile, line)) {
             for (const std::string& stat : desiredStats) {
                 if (line.find(stat) == 0) {
                     std::cout << line << std::endl;
                 }
             }
         }
     } else {
         std::cerr << "Failed to read /proc/meminfo." << std::endl;
     }
 }
Referenced by main().
readFromFile()
std::string readFromFile (const std::string & filename)
File containing functions to display system information TODO
Definition at line 13 of file sysstats.cpp.
{
     std::ifstream file(filename);
     if (!file.is_open()) {
         return "Error: Unable to read " + filename;
     }
     std::ostringstream buffer;
     buffer << file.rdbuf();
     return buffer.str();
 }
Referenced by cpu_temp(), and cpu_usage().